name: Snyk Python Scan

on:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '21 9 * * 3' # At 9:19 on Wednesday

permissions:
  contents: read

jobs:
  snyk:
    # Environment variables required for Snyk to run
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    # Permissions required for Snyk to run
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Install the Snyk CLI
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@master

      # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
      - name: Snyk Code test
        run: snyk code test --sarif --sarif-file-output=snyk-code.sarif || true

      # Push the Snyk Code results into GitHub Code Scanning tab
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
