name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@master

      # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
      - name: Snyk Code test
        run: snyk code test --sarif --sarif-file-output=snyk-code.sarif || true

      # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
      - name: Snyk IaC test and report
        run: snyk iac test --report || true

      # Build the Docker image for testing
      - name: Build a Docker image
        run: docker build -t your/image-to-test .

      # Runs Snyk Container (Container and SCA) analysis and uploads result to Snyk.
      - name: Snyk Container test
        run: snyk container test your/image-to-test --file=Dockerfile

      # Push the Snyk Code results into GitHub Code Scanning tab
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
